title = "The Cat Life"
baseURL = "https://blissman.ca"
languageCode = "en-us"
theme = "ananke"
themesDir = "themes"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 5
googleAnalytics = "UA-111786830-1"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  title = "Bliss Man"
  subtitle = "Web Dev. Engineer. Cat Enthusiast."
  description = "This is the personal site of Bliss Man."
  linkedin = "https://ca.linkedin.com/in/blissman"
  github = "https://github.com/blissman"
  twitter = "https://twitter.com/blissmantwit"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/totoro.jpg"
  recent_posts_number = 2
